name: todos_data_source
description: Todos data source package.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  moor: ^3.4.0
  path_provider: ^1.6.14
  path: ^1.7.0
  sqlite3_flutter_libs: ^0.2.0
  todos_domain:
    path: ../todos_domain

dev_dependencies:
  moor_generator: ^3.3.1
  build_runner: ^1.10.2
